services:
  # MCP Server - slim containerized server for API access
  mcp-server:
    #image: vsexample:mcp-server
    build:
        dockerfile: Dockerfile
        context: .
    volumes:
      - .:/workspace
    working_dir: /workspace
    ports:
      - "8000:8000"
    environment:
      - TERM=xterm-256color
      - GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
      - MCP_PROJECT_ROOT=/workspace
      - PYTHONPATH=/workspace
    stdin_open: true
    tty: true
    command: python3 mcp-server.py --project-root /workspace
