name: Build .NET Framework Project

on:
  push:
    branches: [ main, master, claude-code ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.1.1
      
    - name: Restore NuGet packages
      run: nuget restore VSExample.sln
      
    - name: Build solution
      run: msbuild VSExample.sln /p:Configuration=Release /p:Platform="Any CPU"
      
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1.2
      
    - name: Run tests
      run: vstest.console.exe HelloWorld.Tests\bin\Release\HelloWorld.Tests.dll
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: |
          HelloWorld\bin\Release\
          HelloWorld.Tests\bin\Release\